export const INCREMENT_CURRENCY = "INCREMENT_CURRENCY";
export const PURCHASE_UPGRADE = "PURCHASE_UPGRADE";
export const PER_SECOND_INCREMENT = "PER_SECOND_INCREMENT";
export const PURCHASE_PER_SECOND_UPGRADE = "PURCHASE_PER_SECOND_UPGRADE";
